package com.jantvrdik.intellij.latte.lexer;

import com.intellij.lexer.FlexAdapter;
import com.intellij.lexer.Lexer;
import com.intellij.lexer.MergingLexerAdapter;
import com.intellij.psi.tree.TokenSet;

import static com.jantvrdik.intellij.latte.psi.LatteTypes.*;

/**
 * Adapter for {@link LatteTopLexer} which is generated by JFlex to IntelliJ's interface
 * {@link Lexer}.
 *
 * Also merges any sequence of selected tokens to a single token.
 */
public class LattePhpLexerAdapter extends MergingLexerAdapter {
	public LattePhpLexerAdapter() {
		super(
			new FlexAdapter(new LattePhpLexer((java.io.Reader) null)),
			TokenSet.create(T_TEXT, T_HTML_CLOSE_TAG_OPEN, T_HTML_OPEN_TAG_OPEN, T_HTML_OPEN_TAG_CLOSE, T_HTML_TAG_CLOSE)
		);
	}
}
