package com.jantvrdik.intellij.latte.lexer;

import com.intellij.lexer.FlexAdapter;
import com.intellij.lexer.MergingLexerAdapter;
import com.intellij.psi.tree.TokenSet;
import com.jantvrdik.intellij.latte.psi.LatteTypes;

/**
 * Adapter for {@link LatteMacroLexer} which is generated by JFlex to IntelliJ's interface
 * {@link com.intellij.lexer.Lexer}.
 *
 * Also merges any sequence of T_MACRO_CONTENT tokens to a single T_MACRO_CONTENT token.
 */
public class LatteMacroLexerAdapter extends MergingLexerAdapter {

	public LatteMacroLexerAdapter() {
		super(
			new FlexAdapter(new LatteMacroLexer((java.io.Reader) null)),
			TokenSet.create(LatteTypes.T_MACRO_CONTENT)
		);
	}
}
